rpm-software-management/dnf-plugins-extras

plugins/tracer.py
=> Don't run tracer if --installroot is set; Fix FrostyX/tracer#15

plugins/migrate.py
It would be nice if you could release a new version at least for F22 in a near future (preferably before F22 final release). This bug seems to affect many users.
=> migrate: use Unicodes when migrating YUMDB (RhBug:1223034)

plugins/tracer.py
Please see the FrostyX/tracer#38 for issue description.
=> tracer: don't run tracer when nothing to do; Fix FrostyX/tracer#38

plugins/snapper.py
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> snapper: don't run if nothing in transaction

tests/support.py
With the migration of the kickstart plugin from core plugins to extra plugins, this class is now required for all tests to function.
=> Add BaseCliStub() class to tests/support.py

plugins/local.py
Two crashing bug fixes and a little improvement for plug-in local. Please see the log messages for more details.
=> Littles fixes for plug-in local

tests/support.py
This pull request applies the same patch used in rpm-software-management/dnf-plugins-core#162 to dnf-plugins-extras to solve the same issue. Credit goes to @ignatenkobrain.
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1331981
=> Fix tests by setting priority and cost in RepoStub (rhbz:1331981)

plugins/debug.py, plugins/tracer.py
Fixes for two different messages:
- make an existing string completely translatable
- add a missing space
=> Fix visibile strings

plugins/local.py, plugins/versionlock.py
requires rpm-software-management/dnf#492
=> DNF2: updated plugin to read_config() change (RhBug:1193823)

plugins/kickstart.py
Required by rpm-software-management/dnf#540
=> Change name of function calls according to dnf

dnf-plugins-extras.spec, doc/tracer.rst, plugins/tracer.py
Not finished, please do not merge yet.
=> tracer: rewrite plugin to not use subprocess

.tito/packages/.readme, .tito/tito.props
This should allow to devels to use same build system like for dnf, and dnf-plugins-core.
=> Initialized to use tito.

dnf-plugins-extras.spec, plugins/dnfpluginsextras/__init__.py, plugins/snapper.py, plugins/tracer.py
https://bugzilla.redhat.com/show_bug.cgi?id=1379906
Requires: https://github.com/rpm-software-management/dnf/pull/807
=> Check if pythonX-tracer is removed in transaction (RhBug:1379906)

plugins/rpm_conf.py
It should prenent that attribute doesn't exist.
https://bugzilla.redhat.com/show_bug.cgi?id=1473933
=> Create self._interactive at init (RhBug:1473933)

plugins/system_upgrade.py
https://bugzilla.redhat.com/show_bug.cgi?id=1473435
=> Rework subprocess call to prevent traceback (RhBug:1473435)

dnf-plugins-extras.spec, plugins/system_upgrade.py, tests/test_system_upgrade.py
for https://bugzilla.redhat.com/show_bug.cgi?id=1490832
=> Enable to investigate the issue with system upgrade

dnf-plugins-extras.spec
There is not known any issue that require it.
=> Remove dnf_not_compatibility require

etc/systemd/dnf-system-upgrade.service
https://bugzilla.redhat.com/show_bug.cgi?id=1597657
=> Schedule system-upgrade after system-update-pre.target (RhBug:1597657)

plugins/kickstart.py, tests/support.py
It fixes a problem with groups and it adds support of kikstart excludes
=> Kikstart - change implementation

plugins/system_upgrade.py
As discussed in RHBZ #1758588, the transactions produced at the
`download` and `update` steps can be different in some cases due
to the `DISTUPGRADE` rule being applied to the `download`
transaction but not the `update` transaction. Recording the
removals as well as the installs in the `download` transaction
and re-applying them to the `update` transaction should resolve
at least most of these cases. However, a more correct long-term
fix for this would be for dnf to provide a supported mechanism for
serializing and de-serializing a transaction object, and for the
plugin to use that instead.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
=> system-upgrade: record and reapply removals (#1758588)

plugins/kickstart.py, tests/support.py, tests/test_kickstart.py
It removes call of unknown attribute.
=> [fix] kickstart plugin

doc/system-upgrade.rst, plugins/system_upgrade.py, tests/test_system_upgrade.py
Both commands provide more robust way how to perform upgrade in
workstation environment.
=> Add offline-upgrade and offline-distrosync commands

dnf-plugins-extras.spec, plugins/system_upgrade.py, tests/test_system_upgrade.py
Requires: https://github.com/rpm-software-management/dnf/pull/1589
Based on: https://github.com/rpm-software-management/dnf-plugins-extras/pull/171
=> Store reasons for reboot transactions

.git-commit-template, README.rst
The content is similar to dnf-plugins-core.
Also introduce changelog metadata in commit messages, so that
changelog can be automatically generated while staying useful.
=> README: Add Installation, Contribution, etc.

dnf-plugins-extras.spec
= changelog =
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1863434
=> spec: Fix building with new cmake macros

dnf-plugins-extras.spec, plugins/system_upgrade.py
Requires:
https://github.com/rpm-software-management/libdnf/pull/1029
https://github.com/rpm-software-management/dnf/pull/1659
=> Use Transaction Store/Replay in system upgrade

plugins/system_upgrade.py
dnf automatically cleans up packages used in a transaction, this can be
configured by `keepcache` option.
cachedir still gets cleaned up completely but it is hardcoded to:
`var/lib/dnf/system-upgrade` and cannot be overwritten.
For: https://github.com/rpm-software-management/dnf-plugins-extras/issues/200
https://bugzilla.redhat.com/show_bug.cgi?id=2024430
=> Cleaning up destdir is not necessary, dnf does it (RhBug:2024430)

dnf-plugins-extras.spec, doc/rpmconf.rst, plugins/rpm_conf.py
I have recently contributed "unattended mode" of operation to rpmconf, now it would nice if dnf-plugin-rpmconf would support it.
https://github.com/xsuchy/rpmconf/pull/45
=> Feature Request: implement unattended mode config option
