rpm-software-management/dnf-plugins-extras

dnf-plugins-extras.spec

Note it's not tested but it should work. Without this patch the plugins can be broken with dnf-1.1.2+. Please, do a new build so we can include it into one update with DNF. Thanks.

spec: adapt to dnf-1.1.2 packaging in F23

---

plugins/leaves.py

Speeds up one run() from ~2.6 seconds to ~1.1 on my system.

leaves: Reuse query instead of constructing fresh one for each package

---

po/lt.po

If system language is set to lithuanian no plugin is working. Similar issue https://bugzilla.redhat.com/show_bug.cgi?id=1283599#c11
```
Feb 16 18:02:15 ERROR Nepavyko įkelti įskiepio: versionlock
Feb 16 18:02:15 SUBDEBUG
Traceback (most recent call last):
File "/usr/lib/python3.4/site-packages/dnf/plugin.py", line 124, in import_modules
module = importlib.import_module(name)
File "/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
File …
```

fix plural forms of lithuanian

---

doc/index.rst

It will add links for DNF, DNF-plugins-core, and Hawkey documentations into
index page.

Add link for other project documentation pages

---

dnf-plugins-extras.spec
doc/rpmconf.rst
etc/dnf/plugins/CMakeLists.txt
etc/dnf/plugins/rpmconf.conf
plugins/rpm_conf.py
tests/test_rpmconf.py

- add /etc/dnf/plugins/rpmconf.conf
- can configure rpmconf frontend (partly RhBug [990444](https://bugzilla.redhat.com/show_bug.cgi?id=990444))
- can configure rpmconf to simply display diffs
- disable plugin with `dnf --assume[yes|no]` / no tty \(RhBugs [1211344](https://bugzilla.redhat.com/show_bug.cgi?id=1211344) and [1213848](https://bugzilla.redhat.com/show_bug.cgi?id=1213848)\)
- catch sys.exit calls from rpmconf so it doesn't quit dnf
- tests for all of the above
read_config call in plugins/rpm_conf.py requires rpm-software-management/dnf#492

More configurable rpmconf

---

dnf-plugins-extras.spec
doc/torproxy.rst
etc/dnf/plugins/CMakeLists.txt
etc/dnf/plugins/torproxy.conf
plugins/torproxy.py

This plugin will make sure that tor is enabled for packages
downloads and will verify that tor is working before doing
anything, in order to make sure nothing is leaking by error.
It also configure each connexion to go over a different tor
circuit, to make correlation harder.
This is the first time I wrote a dnf plugin, so I likely forgot something, and would like to get a review before merging. I am not sure if I should include PO update in the PR, so I left them out.

DNF plugin that automatically use tor

---

doc/snapper.rst
plugins/snapper.py

DNF Snapper plugin took snapshot after transaction run. That is too late. This snapshot is unusable for recovery if transaction failed. 
https://bugzilla.redhat.com/show_bug.cgi?id=1248806

snapper: Create pair of snapshots (RhBug:1248806) 

---

doc/system-upgrade.rst
plugins/kickstart.py
plugins/rpm_conf.py
plugins/snapper.py
plugins/system_upgrade.py
plugins/torproxy.py
plugins/tracer.py
tests/test_system_upgrade.py

It should help user to realize that there could be an issue when system is not
fully upgraded.
The patch also enhance the documentation.
https://bugzilla.redhat.com/show_bug.cgi?id=1225442
Requires: https://github.com/rpm-software-management/dnf/pull/841

Add warn to ensure that system is fully upgraded (RhBug:1225442)

---

plugins/system_upgrade.py

It should prevent restart loop in case of problems with loading of repository
caches.

Run remove symlink during configure_upgrade for system-upgrade

---

plugins/system_upgrade.py

It should prevent upgrading expired metadata during reboot.

Add demands.fresh_metadata=false for syste_upgrade

---

etc/systemd/dnf-system-upgrade.service
plugins/system_upgrade.py
tests/test_system_upgrade.py

Also removing now empty file /system-update/.dnf-system-upgrade
originally was this PR https://github.com/rpm-software-management/dnf-plugins-extras/pull/108 which I accidentally closed.

Releasever for system-upgrade is now set in pre_configuration()

---

plugins/system_upgrade.py

Getter of list type options of new cpp config returns
copy of stored value. That means we cannot use append method
on it.

fix using test tsflag on system-upgrade download

---

doc/system-upgrade.rst

A blank line is needed between the description and synopsis sections.
Without it, the output in both html and man formats is incorrect.
Remove an extra, unnecessary blank line at the end of the synopsis.

doc: fix synopsis formatting in system-upgrade

---

doc/torproxy.rst

The plugin reads from config file key "host", not "hostname".

Error in torproxy plugin documentation

---

tests/support.py

Uses dnf.repo.Repo class instead of faking it by StubRepo.
It is required due to changes in DNF.

Fix: remove RepoStub fake classs from unit tests

---

plugins/system_upgrade.py
tests/test_system_upgrade.py

https://bugzilla.redhat.com/show_bug.cgi?id=1638689
When the install_weak_deps is set to False during the download
(--setopt=install_weak_deps=False), the upgrade fails as some weak
dependencies are missing. Therefore, the option must be reused during
the upgrade.

Save install_weak_deps option to persist through reboot (RhBug:1638689)

---

plugins/system_upgrade.py

https://bugzilla.redhat.com/show_bug.cgi?id=1649745

 [system-upgrade] Fix issues with corrupt/missing statefile (RhBug:1649745)

---

plugins/snapper.py

It prevents of confusing user about failed snapper plugin.

Run transaction hook only if transaction

---

dnf-plugins-extras.spec
plugins/torproxy.py

Plugins get parser from DNF.
Don't rely on iniparse module and don't import it.

Remove dependency on iniparse

---

scripts/lint

tox.ini has 100 and scripts/lint had 82. As snapper and system_upgrade plugins have several lines with length more than 82 but less than 100 I assume definitive length is 100.

[lint]: follow tox.ini/flake8 with line length

---

doc/index.rst

The kickstart plugin wasn't listed in the doc TOC.  This should fix the issue.

Add missing doc TOC

---

plugins/system_upgrade.py
tests/test_system_upgrade.py

Option module_platform_id is necessary to perform a system upgrade and switch to
a new platform.

[system-upgrade] Save module_platform_id config option

---

plugins/showvars.py

There was a minor error in the use of `dict_keys` and the loop that prevented it from executing except on python2.7.
This is corrected so it now works as it should.

Permit return of list or dict_keys

---

plugins/system_upgrade.py

Os-release will provide the new key with url with help for
system-upgrade.
https://bugzilla.redhat.com/show_bug.cgi?id=1747408

Provide distro specific url for help with system-upgrade (RhBug:1747408)

---

tests/test_rpmconf.py

It should also fix our copr nightly builds for F31 and F32.

Fix tests for Fedora > 30, rpmconf changed output

---

plugins/system_upgrade.py

After direct removal of packages in upgrade transaction, it is not
needed to look for removal of unused dependencies. Also in some cases it
could trigger reinstall step of some packages. Consequence is
requirement of additional downloads, that are not allowed during
the reboot.
https://bugzilla.redhat.com/show_bug.cgi?id=1764169

Set clean_requirements_on_remove=False during remove (RhBug:1764169)

---

dnf-plugins-extras.spec
doc/CMakeLists.txt
doc/conf.py

Moves the man pages for the plugins from "dnf.plugin.PLUGIN" to
"dnf-PLUGIN" to follow the established convention for man pages of
binaries with commands.
https://bugzilla.redhat.com/show_bug.cgi?id=1706386

[doc] move manpages for plugins to "dnf-PLUGIN" (RhBug:1706386)

---

plugins/system_upgrade.py

New output:
sudo dnf system-upgrade download --releasever=31
Before you continue ensure that your system is fully upgraded by running
"dnf --refresh upgrade". Do you want to continue [y/N]: N
Operation aborted.
https://bugzilla.redhat.com/show_bug.cgi?id=1797427

Do not show Operation aborted as an error (RhBug:1797427)

---

setup.cfg

tox.ini is not read by the pep8speaks bot, setup.cfg is. Unifying the
line length limit with what is used in dnf now.

Move tox.ini -> setup.cfg and increase line length to 120

---

doc/system-upgrade.rst
plugins/system_upgrade.py

If the DNF_SYSTEM_UPGRADE_NO_REBOOT env variable is set, the plugin will
not actually reboot.
= changelog =
msg: Add the DNF_SYSTEM_UPGRADE_NO_REBOOT env variable to control system-upgrade reboot.
type: enhancement

system-upgrade: Add an env variable to control reboot

---

tests/test_system_upgrade.py

======================================================================
ERROR: test_transaction_download (tests.test_system_upgrade.DownloadCommandTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/dnf/rpm/__init__.py", line 39, in detect_releasever
idx = ts.dbMatch('provides', distroverpkg)
File "/usr/lib/python3.8/site-packages/dnf/rpm/transaction.py", line 59, in dbMatch
mi = self.ts.dbMatch(*args, **kwds)
_rpm.error: rpmdb open failed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/builddir/build/BUILD/dnf-plugins-extras-4.0.12/tests/test_system_upgrade.py", line 420, in test_transaction_download …

Set installroot in tmp dir to avoid problems with unittests

---

tests/test_system_upgrade.py

Fixes running tests on Fedora 31.
Sets the installroot to the default "/" in the mocked cli.base.conf. The
whole object is mocked and on Fedora 31 the mocked installroot object wasn't
resulting in anything the command could use. Since all the directories
are already changed to temporary locations, we don't need to set the
installroot to anything special.

test_system_upgrade: Set installroot in the mocked cli

---

po/zanata.xml

Weblate is now used for translations, so zanata config is no longer
needed.

Remove zanata config

---

plugins/system_upgrade.py

If system-upgrade download results in an empty transaction, don't store
it and don't proceed telling the user to reboot.
= changelog =
msg: system-upgrade: Handle empty transaction on download
type: bugfix
resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1917639

system-upgrade: Handle empty transaction on download

---

.github/workflows/ci.yml

Since we have a separate branch for dnf4 in ci-dnf-stack use it to run integration tests.

Run dnf-plugins-extras (dnf4) CI againts dnf-4-stack branch

---

dnf-plugins-extras.spec
tests/test_rpmconf.py

RPM 4.19 removed rpm.fi class. rpmconf tool needs to move to rpm.files class <https://github.com/xsuchy/rpmconf/pull/53>. That in turn breaks tests/test_rpmconf.py which mocks rpmconf internals:
~~~~
tests/test_rpmconf.py:187:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ tests/test_rpmconf.py:58: in __enter__
patch.__enter__()
/usr/lib64/python3.12/unittest/mock.py:1455: in __enter__
original, local = self.get_original()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <unittest.mock._patch object at 0x7fa240b50b00>
def get_original(self):
target = self.getter()
name = self.attribute
original = DEFAULT
local = False
try:
original = target.__dict__[name]
except (AttributeError, KeyError):
original = getattr(target, …

Adapt rpmconf tests to RPM 4.19 without rpm.fi

---

dnf-plugins-extras.spec
doc/snapper.rst
etc/dnf/plugins/CMakeLists.txt
etc/dnf/plugins/snapper.conf
plugins/snapper.py

The snapper plugin fails if the snapper config for `/` is not named `root`:
```
snapper: creating pre_snapshot failed: error.unknown_config: org.freedesktop.DBus.Error.Failed
```
See https://bugzilla.redhat.com/show_bug.cgi?id=2089544
This PR implements a new "snapper_config" setting for specifying which config the plugin uses for creating snapshots. This allows the plugin to function on systems where the root snapper config is named something other than "root".
The setting defaults to "root" (as before) when not set.

snapper: Add support for specifying snapper config name.

---

plugins/rpm_conf.py

Without it, the resulting string will have "... modewithout unattended mode"

Add missing space in rpm_conf.py

---

.github/workflows/ci.yml

This solves the warning:
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Update actions/checkout version

---

README.rst

Companion to https://github.com/rpm-software-management/dnf/pull/2221. @ppisar

README: direct to Libera.Chat instead of Freenode
